version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies
      - pip install django

  build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - '**/*'
